# Config for banmanager (or what ever I'll call it)

mysql:
  url: "jdbc:mysql://localhost:3306/"
  username: "Ban"
  password: "H84VAp3BzBXhWxRR" 
  database: "ban"
  table: "bans"

settings:
  default-reason: "You have been banned from the PortalCraft.Se Servers."
  default-time: "1"
  default-timeformat: "d"